version: 2.1
jobs:
 run_test:
  docker:
   -image: circleci/node:12
  steps:
   -checkout
   -run:
      name: Install npm dependencies
      command:
        npm install --save
build_docker_image:
  docker:
    - image: circleci/node:12
  steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: false
    - run:
        name: Build Docker image
        command: |
          docker build -t nodejswebapp -t shakteesh/nodejswebapp:latest .
          echo $DOCKER_PASSWORD | docker login -u shakteesh --password-stdin
          docker push shakteesh/nopdejswebapp:latest

workflows: 
    build_test:
      jobs:
        - build_test
        - build_docker_image
