#!/bin/sh
 sudo ssh msis@172.16.51.135 <<EOF
 git pull http://github.com/sreepathysois/node-jenkins-app-example.git
 cd ~/node-jenkins-app-example
 npm install 
 pm2 stop app.js
 pm2 start app.js
 exit
EOF
